// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderDeliverySystem.Infrastructure.Persistence;

#nullable disable

namespace OrderDeliverySystem.Infrastructure.Migrations
{
    [DbContext(typeof(OrderDeliveryContext))]
    [Migration("20260423181215_ConfigureRelationshipsAndSeedAgents")]
    partial class ConfigureRelationshipsAndSeedAgents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderDeliverySystem.Domain.Entities.DeliveryAgent", b =>
                {
                    b.Property<Guid>("DeliveryAgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DeliveryAgentId");

                    b.ToTable("DeliveryAgents");

                    b.HasData(
                        new
                        {
                            DeliveryAgentId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            IsActive = true,
                            Name = "Yakubu Kachiro"
                        },
                        new
                        {
                            DeliveryAgentId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            IsActive = true,
                            Name = "Fola Adeyemi"
                        },
                        new
                        {
                            DeliveryAgentId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            IsActive = true,
                            Name = "Chinedu Okonkwo"
                        });
                });

            modelBuilder.Entity("OrderDeliverySystem.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("DeliveryAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("DeliveryAgentId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderDeliverySystem.Domain.Entities.Order", b =>
                {
                    b.HasOne("OrderDeliverySystem.Domain.Entities.DeliveryAgent", "DeliveryAgent")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeliveryAgent");
                });

            modelBuilder.Entity("OrderDeliverySystem.Domain.Entities.DeliveryAgent", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
